"""drop task token estimate and usage columns

Revision ID: 93d92ccaa9cc
Revises: 2ed7040257db
Create Date: 2026-08-19 22:08:07.340411
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93d92ccaa9cc"
down_revision: str | None = "2ed7040257db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_column("token_estimate")
        batch_op.drop_column("tokens_used")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tokens_used", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("token_estimate", sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
