"""add agent_cli to repo and task

Revision ID: 41456592aa95
Revises: 93d92ccaa9cc
Create Date: 2026-08-21 20:09:14.596341
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "41456592aa95"
down_revision: str | None = "93d92ccaa9cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repo", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("agent_cli", sa.String(), server_default="claude", nullable=False)
        )

    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.add_column(sa.Column("agent_cli", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_column("agent_cli")

    with op.batch_alter_table("repo", schema=None) as batch_op:
        batch_op.drop_column("agent_cli")

    # ### end Alembic commands ###
