"""add repo.credential_dir

Revision ID: f634214d376c
Revises: 41456592aa95
Create Date: 2026-08-24 15:09:28.031706
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f634214d376c"
down_revision: str | None = "41456592aa95"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repo", schema=None) as batch_op:
        batch_op.add_column(sa.Column("credential_dir", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repo", schema=None) as batch_op:
        batch_op.drop_column("credential_dir")

    # ### end Alembic commands ###
