"""add preferred_runner_id to tasks

Revision ID: ecf318dfdbe1
Revises: 596be4c1bf2a
Create Date: 2026-07-08 22:07:23.311486
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecf318dfdbe1'
down_revision: str | None = '596be4c1bf2a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_runner_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('preferred_runner_id')

    # ### end Alembic commands ###
